baseURL = 'https://jacobdt23.github.io/'
languageCode = 'en-us'
title = "Jacob's paracord and tech Workshop"

# This ensures Hugo looks for your blog posts correctly
[params]
    mainSections = ["blog"]
    style = "default"

# Clean Menu - Matches your baseof.html
[[menu.main]]
    name = "HOME"
    url = "/"
    weight = 1

[[menu.main]]
    name = "BLOG"
    url = "/blog/"
    weight = 2

[[menu.main]]
    name = "CONTACT"
    url = "/contact/"
    weight = 3
